###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "2.0"
services:

    memcached:
      image: memcached:alpine
      container_name: c80-memcached

    mariadb:
      image: mariadb:10.1
      container_name: c80-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=c80
        - MYSQL_USER=c80
        - MYSQL_PASSWORD=root
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: c80-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: c80-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
